//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int MAHD { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
