//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACC
    {
        public NHACC()
        {
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MANCC { get; set; }
        public string TENNCC { get; set; }
        public string DCHI { get; set; }
        public string DTHOAI { get; set; }
    
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
