//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }
    
        public int MANV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public Nullable<decimal> LUONG { get; set; }
        public string TAIKHOANNV { get; set; }
        public string MATKHAUNV { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
