//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.CHITIETPNs = new HashSet<CHITIETPN>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> MATH { get; set; }
        public Nullable<int> MANCC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public string THONGTIN { get; set; }
        public string HINHANH { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual ICollection<CHITIETPN> CHITIETPNs { get; set; }
        public virtual NHACC NHACC { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
